branches:
  only:
  - master
  - xmppmaster
before_install:
- sudo sh -c "echo 'deb https://git.siveo.net xmppmaster mmc-core' > /etc/apt/sources.list.d/pulse.list"
- sudo apt-get update -qq
- sudo apt-get install -y python-sqlalchemy python-mysqldb python-twisted-web python-ldap
  python-gobject xsltproc docbook-xsl dh-autoreconf
- sudo apt-get install -y mmc-core python-mmc-core apt-transport-https
install: sh autogen.sh && ./configure && make && sudo make install
script:
- echo "DONE"
notifications:
  email:
    recipients:
    - yvan.manon@siveo.net
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.net#pulse-fr"
      - "irc.freenode.net#pulse-en"
    on_success: always #|never|change] # default: always
    on_failure: always #|never|change] # default: always
